/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { RosterInfoDto } from './rosterInfoDto';

export interface AddParticipantsDto {
  /** 로스터 정보 목록 */
  rosters: RosterInfoDto[];
}
