/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface Agreements {
  agreementId: string;
  bipaAgreement: boolean;
  competitionId: string;
  createdAt: string;
  id: number;
  kespaAgreement: boolean;
  parentBirthday?: string;
  parentKey: string;
  parentName?: string;
  parentParticipantConsent?: boolean;
  parentPhoneNumber?: string;
  parentSignature?: string;
  participantConsent: boolean;
  portraitConsent: boolean;
  privacy3rdConsent: boolean;
  privacyConsent: boolean;
  relationship?: string;
  signature?: string;
  updatedAt: string;
  userId: string;
}
