/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface BankAccount {
  account: string;
  bankCode: string;
  createdAt: string;
  id: number;
  oriSeqNo: string;
  updatedAt: string;
  userId: string;
  verified: boolean;
}
