/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface BracketStructureParticipantDto {
  /** 참가 로스터 ID들 */
  rosterId: number;
}
