/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface BracketFormatOptionsDto {
  /** 3/4위전 진행 여부 (싱글 엘리미네이션에서 사용) */
  hasThirdPlaceMatch?: boolean;
}
