/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { Bracket } from './bracket';
import type { BracketGroupParticipant } from './bracketGroupParticipant';
import type { Round } from './round';

export interface BracketGroup {
  bracket: Bracket;
  bracketId: number;
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
  id: number;
  name: string;
  participants: BracketGroupParticipant[];
  rounds: Round[];
  updatedAt: string;
}
