/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface BracketGroupOverviewRoundDto {
  /** 세트 방식 */
  bestOf: number;
  /** 라운드 ID */
  id: number;
  /**
   * 라운드 이름
   * @nullable
   */
  name?: string | null;
  /** 라운드 번호 */
  roundNumber: number;
  /**
   * 경기 날짜 (YYYY-MM-DD)
   * @nullable
   */
  scheduledDate?: string | null;
  /**
   * 경기 시간 (HH:mm:ss)
   * @nullable
   */
  scheduledTime?: string | null;
}
