/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { BracketGroup } from './bracketGroup';
import type { Roster } from './roster';

export interface BracketGroupParticipant {
  bracketGroup: BracketGroup;
  bracketGroupId: number;
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
  id: number;
  roster: Roster;
  rosterId: number;
  /** @nullable */
  seed: number | null;
  updatedAt: string;
}
