/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface Checkin {
  competitionId: string;
  createdAt: string;
  /** Game Type (e.g. LOL, VALORANT) */
  gameType?: string;
  id: number;
  userId: string;
}
