/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface CheckTeamNameDto {
  /** competitionId of team */
  competitionId: string;
  /** name of team */
  name: string;
}
