/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

/**
 * status of competition
 * @nullable
 */
export type ChildCompetitionDtoStatus = typeof ChildCompetitionDtoStatus[keyof typeof ChildCompetitionDtoStatus] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChildCompetitionDtoStatus = {
  opend: 'opend',
  closed: 'closed',
} as const;
