/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { DocumentDto } from './documentDto';
import type { ChildCompetitionDtoGameTypeItem } from './childCompetitionDtoGameTypeItem';
import type { NoticeDto } from './noticeDto';
import type { ChildCompetitionDtoStatus } from './childCompetitionDtoStatus';

export interface ChildCompetitionDto {
  /**
   * competition alias
   * @nullable
   */
  alias?: string | null;
  applicationEndedAt?: string;
  applicationForm: string;
  applicationStartedAt?: string;
  competitionEndedAt?: string;
  competitionId: string;
  competitionStartedAt?: string;
  description: string;
  documents: DocumentDto[];
  /** Due date of parent competition */
  dueDate: string;
  fullTitle: string;
  /** game type of competition */
  gameType?: ChildCompetitionDtoGameTypeItem[];
  id: number;
  /**
   * minor consent content
   * @nullable
   */
  minorConsent?: string | null;
  notice: NoticeDto;
  /**
   * organization title of competition
   * @nullable
   */
  organizationTitle?: string | null;
  organizer: string;
  organizerUrl: string;
  /**
   * parent competition id
   * @nullable
   */
  parentCompetitionId?: string | null;
  privacyPolicy: string;
  /**
   * status of competition
   * @nullable
   */
  status: ChildCompetitionDtoStatus;
  thumbnail: string;
  title: string;
}
