/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { Competition } from './competition';

export type CompetitionsControllerFindHostingCompetitions200 = {
  data?: Competition[];
};
