/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { CompetitionDto } from './competitionDto';
import type { ParentCompetitionDto } from './parentCompetitionDto';

export type CompetitionsControllerFindAllGroup200Item = CompetitionDto | ParentCompetitionDto;
