/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface CreateAgreementDto {
  bipaAgreement?: boolean;
  competitionId: string;
  kespaAgreement?: boolean;
  participantConsent?: boolean;
  portraitConsent?: boolean;
  privacy3rdConsent?: boolean;
  privacyConsent?: boolean;
  signature?: string;
}
