/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface CreateFCOnlineCardDto {
  /** achievement date of player */
  achievementDate: string;
  /** division of player */
  division: string;
  /** level of player */
  level: number;
  /** nickname of player */
  nickname: string;
  /** notOwner of player */
  notOwner?: boolean;
  /** ouid of player */
  ouid: string;
}
