/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface CreateQrDto {
  /** Competition ID */
  competitionId: string;
  /** Display date */
  displayDate: string;
  /** Game type */
  gameType: string;
}
