/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface CreateDocumentDto {
  /** 서류 설명 */
  description?: string;
  /** 미성년자 기준 생년월일(tag가 parent일 때만 사용) */
  minorBirthDate?: string;
  /** 서류 이름 */
  name: string;
  /** 서류 태그(식별자) */
  tag?: string;
}
