/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { CreateBracketDtoFormat } from './createBracketDtoFormat';
import type { BracketGroupInfoDto } from './bracketGroupInfoDto';

export interface CreateBracketDto {
  /** 대진 포맷 */
  format: CreateBracketDtoFormat;
  /** (조 편성할 경우) 그룹들의 생성 정보 */
  groups?: BracketGroupInfoDto[];
  /** 스테이지 ID */
  stageId: number;
  /** 스테이지 이름 */
  stageName: string;
}
