/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface CreateLolCardDto {
  /** level of player */
  level: number;
  /** nickname of player */
  nickname: string;
  /** notOwner of player */
  notOwner?: boolean;
  /** profile picture of player */
  profilePicture: string;
  /** puuid of player */
  puuid: string;
  /** rank of player */
  rank: string;
  /** tier of player */
  tier: string;
}
