/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface File {
  competitionId: string;
  createdAt: string;
  fileId: string;
  fileName: string;
  id: number;
  reason?: string;
  status: string;
  tag: string;
  updatedAt: string;
  userId: string;
}
