/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { GameTypeDtoGameMode } from './gameTypeDtoGameMode';

export interface GameTypeDto {
  gameId: string;
  gameMode: GameTypeDtoGameMode;
  id: string;
  /** 팀 명단 확인 여부 */
  isRosterConfirmed?: boolean;
  /** 후보 플레이어 최대 인원 */
  maxSubstituteCount?: number;
  /** 팀 수 */
  numberOfTeams?: number;
  /** 팀당 플레이어 수 */
  playersPerTeam?: number;
}
