/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

/**
 * 게임 모드
 */
export type GameTypeGameMode = typeof GameTypeGameMode[keyof typeof GameTypeGameMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GameTypeGameMode = {
  SOLO: 'SOLO',
  TEAM: 'TEAM',
} as const;
