/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { SetResultWithStatsDto } from './setResultWithStatsDto';

export interface GetSetParticipantStatsResponseDto {
  /** 세트 결과 목록 */
  setResults: SetResultWithStatsDto[];
}
