/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

/**
 * 승리 팀
 */
export type ManageMatchSetsDtoWinnerTeam = typeof ManageMatchSetsDtoWinnerTeam[keyof typeof ManageMatchSetsDtoWinnerTeam];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ManageMatchSetsDtoWinnerTeam = {
  A: 'A',
  B: 'B',
} as const;
