/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { MatchParticipant } from './matchParticipant';
import type { MatchSetResult } from './matchSetResult';
import type { MatchSetParticipantStatStatPayload } from './matchSetParticipantStatStatPayload';

export interface MatchSetParticipantStat {
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
  id: number;
  matchParticipant: MatchParticipant;
  matchParticipantId: number;
  matchSetResult: MatchSetResult;
  matchSetResultId: number;
  statPayload: MatchSetParticipantStatStatPayload;
  updatedAt: string;
}
