/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { LolCard } from './lolCard';
import type { FCOnlineCard } from './fCOnlineCard';

export type MemberDataGameCard = LolCard | FCOnlineCard;
