/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { CreateDocumentDto } from './createDocumentDto';
import type { ModifyCompetitionDtoGameTypeItem } from './modifyCompetitionDtoGameTypeItem';
import type { ModifyCompetitionDtoStatus } from './modifyCompetitionDtoStatus';

export interface ModifyCompetitionDto {
  /** competition alias */
  alias?: string;
  /** application end date */
  applicationEndedAt?: string;
  /** application form of competition */
  applicationForm?: string;
  /** application start date */
  applicationStartedAt?: string;
  /** competition end date */
  competitionEndedAt?: string;
  /** competition start date */
  competitionStartedAt?: string;
  /** description of competition */
  description?: string;
  /** documents of competition */
  documents?: CreateDocumentDto[];
  /** full name of competition */
  fullTitle?: string;
  /** game type of competition */
  gameType?: ModifyCompetitionDtoGameTypeItem[];
  /** minor consent of competition */
  minorConsent?: string;
  /** notice of competition */
  notice?: string;
  /** organization title of competition */
  organizationTitle?: string;
  /** organizer of competition */
  organizer?: string;
  /** organizer url of competition */
  organizerUrl?: string;
  /** parent competition id */
  parentCompetitionId?: string;
  /** privacy policy of competition */
  privacyPolicy?: string;
  /** status of competition */
  status: ModifyCompetitionDtoStatus;
  /** thumbnail of competition */
  thumbnail?: string;
  /** name of competition */
  title?: string;
}
