/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { MemberData } from './memberData';
import type { Document } from './document';
import type { Team } from './team';

export interface MyTeamResonse {
  /** gameId of team */
  gameId: string;
  /** members info */
  members: MemberData[];
  /** status of team */
  missingDocs: Document[];
  /** team info */
  team: Team;
}
