/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface PaginationResponseDto {
  /** Number of items per page */
  limit: number;
  /** Current page number */
  page: number;
  /** Total number of items */
  totalItems: number;
  /** Total number of pages */
  totalPages: number;
}
