/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface ParticipantDto {
  /** 로스터 ID */
  rosterId: number;
  /** 슬롯 번호 */
  slotNumber: number;
}
