/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface PassInfo {
  birthday: string;
  foreigner_v2: boolean;
  gender: string;
  name: string;
  phone: string;
  unique_in_site: string;
  unique_key: string;
}
