/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface ProCheckin {
  checkinAt?: string;
  checkinId: string;
  code: string;
  createdAt: string;
  id: string;
  matchId?: string;
  reason?: string;
  refereeId: string;
  status?: string;
  userId: string;
}
