/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { ProCompetition } from './proCompetition';

export interface ProHistoryWithCompetition {
  averageAssists: number;
  averageDeaths: number;
  averageKDA: number;
  averageKills: number;
  competition: ProCompetition;
  competitionId: string;
  createdAt: string;
  finalPlacement: string;
  id: string;
  /** @nullable */
  individualAward: string | null;
  losses: number;
  matches: number;
  proPlayerId: string;
  teamName: string;
  totalAssists: number;
  totalDeaths: number;
  totalKills: number;
  userId: string;
  winRate: string;
  wins: number;
}
