/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

/**
 * 심판 역할 (main: 주심, assistant: 부심)
 */
export type ProMatchRefereeRole = typeof ProMatchRefereeRole[keyof typeof ProMatchRefereeRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProMatchRefereeRole = {
  main: 'main',
  assistant: 'assistant',
} as const;
