/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { ProMatchRefereeRole } from './proMatchRefereeRole';

export interface ProMatchReferee {
  createdAt: string;
  id: number;
  /** ProMatch의 matchId */
  matchId: string;
  /**
   * 심판의 경기 노트 - 판정 근거, 특이사항, 관찰 사항 등
   * @nullable
   */
  matchNote: string | null;
  /** 심판 ID */
  refereeId: string;
  /** 심판 역할 (main: 주심, assistant: 부심) */
  role: ProMatchRefereeRole;
  /**
   * 심판이 경기를 제출한 시간
   * @nullable
   */
  submittedAt: string | null;
  /**
   * 담당하는 팀 이름
   * @nullable
   */
  teamName: string | null;
  updatedAt: string;
}
