/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export type QrControllerGetQrCodeByGameAndDateParams = {
/**
 * Game type (e.g. LOL, OVERWATCH)
 */
gameType?: string;
/**
 * Date to query (YYYY-MM-DD)
 */
date?: string;
/**
 * Competition ID (e.g. HANSIN2025)
 */
competitionId?: string;
};
