/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { Roster } from './roster';
import type { RosterControllerFindAllByQuery200AllOfMeta } from './rosterControllerFindAllByQuery200AllOfMeta';

export type RosterControllerFindAllByQuery200AllOf = {
  data?: Roster[];
  meta?: RosterControllerFindAllByQuery200AllOfMeta;
};
