/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { GameType } from './gameType';
import type { RosterPlayer } from './rosterPlayer';
import type { RosterTeam } from './rosterTeam';

export interface Roster {
  /**
   * Created At
   */
  createdAt: string;
  /**
   * Deleted At
   * @nullable
   */
  deletedAt: string | null;
  gameType: GameType;
  gameTypeId: number;
  id: number;
  /**
   * Player
   * @nullable
   */
  player: RosterPlayer;
  /**
   * Player ID
   * @nullable
   */
  playerId: number | null;
  /**
   * Team
   * @nullable
   */
  team: RosterTeam;
  /**
   * Team ID
   * @nullable
   */
  teamId: number | null;
  /**
   * Updated At
   */
  updatedAt: string;
}
