/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface RosterInfoDto {
  /** 로스터 ID */
  id: number;
  /**
   * 배정 순번(시드 번호). 부전승(BYE)일 경우 NULL
   * @nullable
   */
  seed: number | null;
}
