/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { RosterControllerFindOne200Data } from './rosterControllerFindOne200Data';

export type RosterControllerFindOne200 = {
  /** @nullable */
  data?: RosterControllerFindOne200Data;
};
