/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { Referee } from './referee';
import type { Round } from './round';

export interface RoundReferee {
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
  referee: Referee;
  refereeId: number;
  round: Round;
  roundId: number;
  updatedAt: string;
}
