/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { BracketGroup } from './bracketGroup';
import type { Match } from './match';
import type { RoundReferee } from './roundReferee';

export interface Round {
  bestOf: number;
  bracketGroup: BracketGroup;
  bracketGroupId: number;
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
  id: number;
  matches: Match[];
  /** @nullable */
  name: string | null;
  roundNumber: number;
  roundReferees: RoundReferee[];
  /** @nullable */
  scheduledDate: string | null;
  /** @nullable */
  scheduledTime: string | null;
  updatedAt: string;
  /** @nullable */
  venue: string | null;
}
