/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { SetParticipantStatSaveDto } from './setParticipantStatSaveDto';

export interface SaveSetParticipantStatsDto {
  /** 세트 참여자 Stat 목록 */
  setParticipantStats: SetParticipantStatSaveDto[];
}
