/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { SetResultSaveDto } from './setResultSaveDto';

export interface SaveSetResultsDto {
  /** 결과 메모 */
  resultMemo?: string;
  /** 세트 결과 목록 */
  setResults?: SetResultSaveDto[];
}
