/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface SetResultSaveDto {
  /** 세트 결과 ID */
  id: number;
  /** 스크린샷 URL */
  screenshotUrl?: string;
  /** 승자 로스터 ID */
  winnerRosterId?: number;
}
