/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { SignInWithPassResponseDtoRole } from './signInWithPassResponseDtoRole';
import type { User } from './user';

export interface SignInWithPassResponseDto {
  existingUser?: boolean;
  role: SignInWithPassResponseDtoRole;
  token: string;
  user: User;
}
