/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { TeamRoster } from './teamRoster';

export interface Team {
  competitionId: string;
  confirmed: boolean;
  createdAt: string;
  gameId: string;
  id: number;
  leaderId: string;
  name: string;
  organization?: string;
  /**
   * Roster
   * @nullable
   */
  roster: TeamRoster;
  teamCode: string;
  updatedAt: string;
}
