/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface UpdateUserDto {
  address?: string;
  dateOfBirth?: string;
  email?: string;
  isForeigner?: boolean;
  lolMaxTier?: string;
  phoneNumber?: string;
  pushToken?: string;
  signature?: string;
  university?: string;
}
