/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface AppVersion {
  appStoreUrl: string;
  forceUpdate: boolean;
  id: number;
  latestVersion: string;
  minimumVersion: string;
  playStoreUrl: string;
  updatedAt: string;
  updateMessage: string;
}
