/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface BracketStructureRoundDto {
  /** 세트 방식 (1=단판, 3=3판2선승, 5=5판3선승) */
  bestOf: number;
  /** 라운드 이름 */
  name?: string;
  /** 배정 심판 ID 목록 */
  refereeIds: number[];
  /** 라운드 번호 (1, 2, ...) */
  roundNumber: number;
  /** 경기 일자 (YYYY-MM-DD) */
  scheduledDate: string;
  /** 경기 시간 (HH:mm:ss) */
  scheduledTime: string;
  /** 임시 라운드 ID (프론트/초기화용) */
  tempId: string;
  /** 경기 장소 */
  venue: string;
}
