/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { BracketGroupOverviewResponseDto } from './bracketGroupOverviewResponseDto';

export type BracketGroupControllerGetBracketGroupOverview200 = {
  data?: BracketGroupOverviewResponseDto;
};
