/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { BracketFormatOptions } from './bracketFormatOptions';
import type { BracketGroup } from './bracketGroup';

export interface Bracket {
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
  format: string;
  formatOptions: BracketFormatOptions;
  groups: BracketGroup[];
  id: number;
  stageId: number;
  updatedAt: string;
  useGroups: boolean;
}
