/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { BracketGroupOverviewMatchDto } from './bracketGroupOverviewMatchDto';
import type { BracketGroupOverviewRoundDto } from './bracketGroupOverviewRoundDto';

export interface BracketGroupOverviewResponseDto {
  /** 매치 목록 */
  matches: BracketGroupOverviewMatchDto[];
  /** 라운드 목록 */
  rounds: BracketGroupOverviewRoundDto[];
}
