/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { BracketStructureMatchDto } from './bracketStructureMatchDto';
import type { BracketStructureRoundDto } from './bracketStructureRoundDto';

export interface BracketStructureGroupDto {
  /** 그룹(조) ID */
  id: number;
  /** 매치 목록 */
  matches: BracketStructureMatchDto[];
  /** 라운드 목록 */
  rounds: BracketStructureRoundDto[];
}
