/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface BrawlStarsCard {
  createdAt: string;
  expLevel: number;
  gameCardId: string;
  highestTrophies: number;
  id: number;
  nickname: string;
  notOwner: boolean;
  playerTag: string;
  reason?: string;
  screenshotFileId: string;
  screenshotFileName: string;
  status: string;
  /** Supercell ID */
  supercellId?: string;
  trophies: number;
  updatedAt: string;
  userId: string;
}
