/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type {GameType} from './gameType';
import type {Workspace} from './workspace';

export interface Competition {
  alias: string;
  applicationEndedAt: string;
  applicationForm: string;
  applicationStartedAt: string;
  competitionEndedAt: string;
  competitionId: string;
  competitionStartedAt: string;
  description: string;
  fullTitle: string;
  gameTypes: GameType[];
  id: number;
  minorConsent?: string;
  notice: string;
  organizationTitle?: string;
  organizer: string;
  organizerUrl: string;
  /** @nullable */
  parentCompetitionId: string | null;
  privacyPolicy: string;
  status: string;
  thumbnail: string;
  title: string;
  workspace?: Workspace;
  /**
   * workspace id
   * @nullable
   */
  workspaceId: string | null;

  hasBracket: boolean;
}
