/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

/**
 * enumName: CompetitionCategoryType (Region, Gender, Age)
 */
export type CompetitionCategoryType = typeof CompetitionCategoryType[keyof typeof CompetitionCategoryType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CompetitionCategoryType = {
  Region: 'Region',
  Gender: 'Gender',
  Age: 'Age',
} as const;
