/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface CreateTeamDto {
  /** competitionId of team */
  competitionId: string;
  gameId: string;
  /** Team name */
  name: string;
  /** organization of team */
  organization?: string;
}
