/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { BracketGroupDto } from './bracketGroupDto';

export interface CreateBracketResponseDto {
  /** 생성된 대진표 그룹 목록 */
  bracketGroups: BracketGroupDto[];
  /** 생성된 대진표 ID */
  bracketId: number;
}
