/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface CreateBrawlStarsCardDto {
  /** experience level of player */
  expLevel: number;
  /** highest trophies of player */
  highestTrophies: number;
  /** nickname of player */
  nickname: string;
  /** notOwner of player */
  notOwner?: boolean;
  /** player tag */
  playerTag: string;
  /** supercell id of player */
  supercellId: string;
  /** current trophies of player */
  trophies: number;
}
