/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { CreateDocumentDto } from './createDocumentDto';
import type { CreateCompetitionDtoGameTypeItem } from './createCompetitionDtoGameTypeItem';
import type { NoticeDto } from './noticeDto';
import type { CreateCompetitionDtoStatus } from './createCompetitionDtoStatus';

export interface CreateCompetitionDto {
  /** competition alias */
  alias?: string;
  /**
   * application end date
   * @nullable
   */
  applicationEndedAt?: string | null;
  /** application form of competition */
  applicationForm: string;
  /**
   * application start date
   * @nullable
   */
  applicationStartedAt?: string | null;
  /**
   * competition end date
   * @nullable
   */
  competitionEndedAt?: string | null;
  /**
   * competition start date
   * @nullable
   */
  competitionStartedAt?: string | null;
  /** description of competition */
  description: string;
  /** documents of competition */
  documents?: CreateDocumentDto[];
  /** full title of competition */
  fullTitle: string;
  /** game type of competition */
  gameType: CreateCompetitionDtoGameTypeItem[];
  /** Auto increment id */
  id: string;
  /**
   * minor consent of competition
   * @nullable
   */
  minorConsent?: string | null;
  /** notice of competition */
  notice: NoticeDto;
  /**
   * organization title of competition
   * @nullable
   */
  organizationTitle?: string | null;
  /** organizer of competition */
  organizer: string;
  /** organizer url of competition */
  organizerUrl: string;
  /**
   * parent competition id
   * @nullable
   */
  parentCompetitionId?: string | null;
  /** privacy policy of competition */
  privacyPolicy: string;
  /** status of competition */
  status: CreateCompetitionDtoStatus;
  /** thumbnail of competition */
  thumbnail: string;
  /** name of competition */
  title: string;
}
