/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface Document {
  /** 대회 ID */
  competitionId: string;
  /** 서류 설명 */
  description: string;
  id: number;
  /** @nullable */
  minorBirthDate?: string | null;
  /** 서류 이름 */
  name: string;
  /** 서류 태그 */
  tag: string;
}
