/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface FCOnlineCard {
  achievementDate: string;
  createdAt: string;
  division: string;
  gameCardId: string;
  id: number;
  level: number;
  nickname: string;
  notOwner: boolean;
  ouid: string;
  reason?: string;
  screenshotFileId: string;
  screenshotFileName: string;
  status: string;
  updatedAt: string;
  userId: string;
}
