/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { LolCard } from './lolCard';
import type { FCOnlineCard } from './fCOnlineCard';
import type { ValCard } from './valCard';
import type { OWCard } from './oWCard';
import type { BrawlStarsCard } from './brawlStarsCard';
import type { PubgMobileCard } from './pubgMobileCard';
import type { StreetFighterCard } from './streetFighterCard';
import type { KartRiderCard } from './kartRiderCard';
import type { EternalReturnsCard } from './eternalReturnsCard';
import type { EFootballCard } from './eFootballCard';
import type { PokemonUniteCard } from './pokemonUniteCard';
import type { KingOfFightersCard } from './kingOfFightersCard';

export type GameControllerUpdateNickname200 = LolCard | FCOnlineCard | ValCard | OWCard | BrawlStarsCard | PubgMobileCard | StreetFighterCard | KartRiderCard | EternalReturnsCard | EFootballCard | PokemonUniteCard | KingOfFightersCard;
