/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { Competition } from './competition';
import type { GameTypeGameMode } from './gameTypeGameMode';

export interface GameType {
  competition: Competition;
  competitionId: string;
  gameId: string;
  /** 게임 모드 */
  gameMode: GameTypeGameMode;
  gameTypeId: string;
  id: number;
  /** 팀 명단 잠금 여부 */
  isRosterConfirmed?: boolean;
  /** 후보 플레이어 최대 인원 */
  maxSubstituteCount?: number;
  /** 게임 타입 이름 */
  name: string;
  /** 팀 수 */
  numberOfTeams?: number;
  /** 팀당 플레이어 수 */
  playersPerTeam?: number;
}
