/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { GameMetaDtoGenre } from './gameMetaDtoGenre';

export interface GameMetaDto {
  cardImageUrl: string;
  genre: GameMetaDtoGenre;
  icon: string;
  id: string;
  krName: string;
  logo: string;
  name: string;
  verifyScreenshotUrl: string;
  verifyScreenshotUrlDetail?: string;
  verifyUrl: string;
}
