/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { SetResultDto } from './setResultDto';

export interface GetSetResultsResponseDto {
  /** 결과 메모 */
  resultMemo?: string;
  /** 결과 제출 일시 */
  resultSubmittedAt?: string;
  /** 결과 제출자 ID */
  resultSubmitterId?: number;
  /** 세트 결과 목록 */
  setResults: SetResultDto[];
}
