/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { Organization } from './organization';
import type { User } from './user';
import type { WorkspaceHost } from './workspaceHost';

export interface Host {
  createdAt: string;
  id: number;
  organization?: Organization;
  /** @nullable */
  organizationId: string | null;
  updatedAt: string;
  user: User;
  userId: number;
  workspaceHosts: WorkspaceHost[];
}
