/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { BracketStructureGroupDto } from './bracketStructureGroupDto';
import type { BracketFormatOptionsDto } from './bracketFormatOptionsDto';

export interface InitializeBracketStructureDto {
  /** 그룹(조)별 라운드/매치 정보 */
  bracketGroups: BracketStructureGroupDto[];
  /** 포맷의 옵션 정보 */
  formatOptions?: BracketFormatOptionsDto;
}
