/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface LolUser {
  gameName: string;
  level: number;
  profilePicture: string;
  puuid: string;
  queueType: string;
  rank?: string;
  tagLine: string;
  tier: string;
}
