/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { ManageMatchSetsDtoWinnerTeam } from './manageMatchSetsDtoWinnerTeam';

export interface ManageMatchSetsDto {
  /** 세트 취소 여부 */
  cancel?: boolean;
  /** 커스텀 승자 이름 (팀 A/B가 아닌 경우) */
  customWinnerName?: string;
  /** 현재 세트 번호 */
  setNumber: number;
  /** A팀 점수 */
  teamAScore?: number;
  /** B팀 점수 */
  teamBScore?: number;
  /** 전체 세트 수 */
  totalSetNumber: number;
  /** 승리 팀 */
  winnerTeam?: ManageMatchSetsDtoWinnerTeam;
}
