/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { ResponseMatchParticipantDto } from './responseMatchParticipantDto';

export type MatchControllerGetMatchParticipantsByQuery200 = {
  data?: ResponseMatchParticipantDto[];
};
