/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { MatchParticipant } from './matchParticipant';
import type { MatchReferee } from './matchReferee';
import type { MatchSetResult } from './matchSetResult';
import type { User } from './user';
import type { Round } from './round';

export interface Match {
  bestOf: number;
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
  id: number;
  loserProgressionMatch: Match;
  loserProgressionMatches: Match[];
  /** @nullable */
  loserProgressionMatchId: number | null;
  matchNumber: number;
  matchParticipants: MatchParticipant[];
  matchReferees: MatchReferee[];
  matchSetResults: MatchSetResult[];
  /** @nullable */
  name: string | null;
  /** @nullable */
  participantsCount: number | null;
  /** @nullable */
  resultMemo: string | null;
  /** @nullable */
  resultSubmittedAt: string | null;
  resultSubmitter: User;
  /** @nullable */
  resultSubmitterId: number | null;
  round: Round;
  roundId: number;
  /** @nullable */
  scheduledDate: string | null;
  /** @nullable */
  scheduledTime: string | null;
  updatedAt: string;
  /** @nullable */
  venue: string | null;
  winnerProgressionMatch: Match;
  winnerProgressionMatches: Match[];
  /** @nullable */
  winnerProgressionMatchId: number | null;
  /** workspace id */
  workspaceId: string;
}
