/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { Match } from './match';
import type { Referee } from './referee';

export interface MatchReferee {
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
  match: Match;
  matchId: number;
  referee: Referee;
  refereeId: number;
  updatedAt: string;
}
