/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { Match } from './match';
import type { MatchSetParticipantStat } from './matchSetParticipantStat';
import type { Roster } from './roster';

export interface MatchSetResult {
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
  id: number;
  match: Match;
  matchId: number;
  matchSetParticipantStats: MatchSetParticipantStat[];
  /** @nullable */
  screenshotUrl: string | null;
  setNumber: number;
  updatedAt: string;
  winnerRoster: Roster;
  /** @nullable */
  winnerRosterId: number | null;
}
