/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { MemberDataGameCard } from './memberDataGameCard';
import type { MemberDataRoster } from './memberDataRoster';
import type { User } from './user';

export interface MemberData {
  competitionId: string;
  confirmed: boolean;
  createdAt: string;
  deletedAt: string;
  final?: boolean;
  gameCard: MemberDataGameCard;
  gameCardId: string;
  gameId: string;
  id: number;
  organization?: string;
  playerId: string;
  position: string;
  reason?: string;
  /**
   * Roster
   * @nullable
   */
  roster: MemberDataRoster;
  status: string;
  /** @nullable */
  teamCode: string | null;
  updatedAt: string;
  /** User */
  user: User;
  userId: string;
}
