/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

/**
 * status of competition
 */
export type ModifyCompetitionDtoStatus = typeof ModifyCompetitionDtoStatus[keyof typeof ModifyCompetitionDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModifyCompetitionDtoStatus = {
  opend: 'opend',
  closed: 'closed',
} as const;
