/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export type ModifyCompetitionDtoGameTypeItem = typeof ModifyCompetitionDtoGameTypeItem[keyof typeof ModifyCompetitionDtoGameTypeItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModifyCompetitionDtoGameTypeItem = {
  lol: 'lol',
  fco: 'fco',
  val: 'val',
  ow2: 'ow2',
  brs: 'brs',
  pgm: 'pgm',
  sfv: 'sfv',
  krt: 'krt',
  ert: 'ert',
  kof: 'kof',
  efo: 'efo',
  pku: 'pku',
} as const;
