/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface NoticeDto {
  brs?: string;
  efo?: string;
  ert?: string;
  fconline?: string;
  kof?: string;
  krt?: string;
  lol?: string;
  pgm?: string;
  pku?: string;
  str?: string;
  val?: string;
}
