/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface Organization {
  createdAt: string;
  id: string;
  name: string;
  updatedAt: string;
}
