/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { CompetitionCategoryType } from './competitionCategoryType';
import type { ParentCompetitionDtoGameTypeItem } from './parentCompetitionDtoGameTypeItem';
import type { NoticeDto } from './noticeDto';
import type { ParentCompetitionDtoStatus } from './parentCompetitionDtoStatus';

export interface ParentCompetitionDto {
  /** Application end date of parent competition */
  applicationEndedAt?: string;
  /** Application start date of parent competition */
  applicationStartedAt?: string;
  /** @nullable */
  childCategoryType?: CompetitionCategoryType;
  /** child competition ids */
  childCompetitionIds?: string[];
  /** Description of parent competition */
  description: string;
  /** Full title of parent competition */
  fullTitle: string;
  /** game type of competition */
  gameType?: ParentCompetitionDtoGameTypeItem[];
  /** uuid */
  id: string;
  notice: NoticeDto;
  /** status of competition */
  status: ParentCompetitionDtoStatus;
  /** Thumbnail image of parent competition */
  thumbnail: string;
  /** Title of parent competition */
  title: string;
}
