/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface ProCompetition {
  competitionId: string;
  createdAt: string;
  eventEndDate: string;
  eventStartDate: string;
  id: number;
  organizer: string;
  regisitrationStartDate: string;
  registrationEndDate: string;
  title: string;
  updatedAt: string;
}
