/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface Qr {
  /** Competition ID (e.g. HANSIN2025) */
  competitionId: string;
  createdAt: string;
  /** Date when the QR code should be shown */
  displayDate: string;
  /** Game type (e.g. LOL, OVERWATCH) */
  gameType: string;
  id: number;
  /** Base64 encoded QR code image */
  qrImageBase64: string;
}
