/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { MatchReferee } from './matchReferee';
import type { RoundReferee } from './roundReferee';
import type { User } from './user';

export interface Referee {
  authority: string;
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
  firstName: string;
  gameName: string;
  id: number;
  issuedDate: string;
  issuedNumber: string;
  lastName: string;
  license: string;
  matchReferees: MatchReferee[];
  nationality: string;
  nativeName: string;
  photoUrl: string;
  roundReferees: RoundReferee[];
  updatedAt: string;
  user: User;
  userId: number;
}
