/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { Competition } from './competition';
import type { GameType } from './gameType';
import type { Referee } from './referee';

export interface RefereeCompetition {
  competition: Competition;
  competitionId: number;
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
  gameType?: GameType;
  /** @nullable */
  gameTypeId: number | null;
  id: number;
  referee: Referee;
  refereeId: number;
  updatedAt: string;
}
