/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface RegisterPlayerDto {
  /** competitionId of player */
  competitionId: string;
  /** gameCardId of player */
  gameCardId: string;
  /** gameId of player */
  gameId: string;
  /** organization of player */
  organization?: string;
  /** position of player */
  position: string;
}
