/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface ReplaceRefereeDto {
  /** Match ID */
  matchId: string;
  /** ID of the new referee to be assigned */
  newRefereeId: string;
  /** ID of the referee to be replaced */
  oldRefereeId: string;
}
