/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export type ResponseGameTypeDtoGameMode = typeof ResponseGameTypeDtoGameMode[keyof typeof ResponseGameTypeDtoGameMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResponseGameTypeDtoGameMode = {
  SOLO: 'SOLO',
  TEAM: 'TEAM',
} as const;
