/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { ResponseGameTypeDto } from './responseGameTypeDto';

export interface ResponseCompetitionDto {
  alias: string;
  applicationEndedAt: string;
  applicationForm: string;
  applicationStartedAt: string;
  competitionEndedAt: string;
  competitionId: string;
  competitionStartedAt: string;
  description: string;
  fullTitle: string;
  gameTypes: ResponseGameTypeDto[];
  id: number;
  minorConsent?: string;
  notice: string;
  organizationTitle?: string;
  organizer: string;
  organizerUrl: string;
  parentCompetitionId: string;
  privacyPolicy: string;
  status: string;
  thumbnail: string;
  title: string;
  /** @nullable */
  workspaceId: string | null;
}
