/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface ResponseResultSubmitUserDto {
  createdAt: string;
  dateOfBirth: string;
  email: string;
  gender: string;
  id: number;
  isForeigner: boolean;
  name: string;
  phoneNumber: string;
  role: string;
  unique_key: string;
  updatedAt: string;
  userId: string;
}
