/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { ResponseRefereeUserDto } from './responseRefereeUserDto';

export interface ResponseRefereeDto {
  authority: string;
  createdAt: string;
  firstName: string;
  gameName: string;
  id: number;
  issuedDate: string;
  issuedNumber: string;
  lastName: string;
  license: string;
  nationality: string;
  nativeName: string;
  photoUrl: string;
  updatedAt: string;
  user: ResponseRefereeUserDto;
  userId: number;
}
