/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface ResponseMatchParticipantDto {
  createdAt: string;
  gameTypeId?: number;
  id: number;
  /** @nullable */
  isWinner: boolean | null;
  rosterId: number;
  slotNumber: number;
  stageId?: number;
  updatedAt: string;
}
