/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { ResponseGameTypeDtoGameMode } from './responseGameTypeDtoGameMode';

export interface ResponseGameTypeDto {
  gameId: string;
  gameMode: ResponseGameTypeDtoGameMode;
  gameTypeId: string;
  id: number;
  isRosterConfirmed: boolean;
  maxSubstituteCount?: number;
  name: string;
  numberOfTeams?: number;
  playersPerTeam?: number;
}
