/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { Player } from './player';

/**
 * Player
 * @nullable
 */
export type RosterPlayer = Player | null;
