/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { RosterControllerFindAllByQueryOrderBy } from './rosterControllerFindAllByQueryOrderBy';

export type RosterControllerFindAllByQueryParams = {
/**
 * Page number for pagination
 */
page?: number;
/**
 * Number of items per page, default is 10, max is 10000
 */
limit?: number;
gameTypeId: number;
orderBy?: RosterControllerFindAllByQueryOrderBy;
};
