/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { RosterControllerSoftRemove200Data } from './rosterControllerSoftRemove200Data';

export type RosterControllerSoftRemove200 = {
  /** @nullable */
  data?: RosterControllerSoftRemove200Data;
};
