/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export type RosterControllerFindAllByQueryOrderBy = typeof RosterControllerFindAllByQueryOrderBy[keyof typeof RosterControllerFindAllByQueryOrderBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RosterControllerFindAllByQueryOrderBy = {
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  '-createdAt': '-createdAt',
  '-updatedAt': '-updatedAt',
} as const;
