/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface SendVerificationResponseDto {
  /** Error details (returned only on failure) */
  error?: string;
  /** Verification code expiration time (returned only on success) */
  expiredAt?: string;
  /** maxAttemptCount */
  maxAttemptCount?: number;
  /** Response message */
  message: string;
  /** Verification request ID (returned only on success) */
  requestId?: string;
  /** 성공 여부 */
  success: boolean;
}
