/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

/**
 * type of notification
 */
export type SendBatchNotiDtoType = typeof SendBatchNotiDtoType[keyof typeof SendBatchNotiDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SendBatchNotiDtoType = {
  DISCORD_LINK: 'DISCORD_LINK',
  KESPA_LINK: 'KESPA_LINK',
  KESPA_LINK_2: 'KESPA_LINK_2',
  TEAM_REMINDER: 'TEAM_REMINDER',
  APPLY_LINK: 'APPLY_LINK',
  REMINDER_1DAY: 'REMINDER_1DAY',
  REMINDER_1HOUR_FC0: 'REMINDER_1HOUR_FC0',
  REMINDER_10MINUTE_FC0: 'REMINDER_10MINUTE_FC0',
  REMINDER_1HOUR_LOL: 'REMINDER_1HOUR_LOL',
  REMINDER_10MINUTE_LOL: 'REMINDER_10MINUTE_LOL',
  ONLINE_SCHEDULE: 'ONLINE_SCHEDULE',
  MATCH_UPDATE: 'MATCH_UPDATE',
  FINAL_CHECKIN: 'FINAL_CHECKIN',
  FINAL_REMINER_1HOUR_LOL: 'FINAL_REMINER_1HOUR_LOL',
  FINAL_REMINER_1HOUR_FC0: 'FINAL_REMINER_1HOUR_FC0',
  PRO_PLAYER: 'PRO_PLAYER',
} as const;
