/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

/**
 * Stat 페이로드
 */
export type SetParticipantStatSaveDtoStatPayload = { [key: string]: unknown };
