/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { SetParticipantStatSaveDtoStatPayload } from './setParticipantStatSaveDtoStatPayload';

export interface SetParticipantStatSaveDto {
  /** 세트 결과 ID */
  matchSetResultId: number;
  /** 참가자 rosterId */
  rosterId: number;
  /** Stat 페이로드 */
  statPayload: SetParticipantStatSaveDtoStatPayload;
}
