/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { SetParticipantStatDto } from './setParticipantStatDto';

export interface SetResultWithStatsDto {
  /** 세트 결과 ID */
  id: number;
  /** 세트 번호 */
  setNumber: number;
  /** 세트 참여자 통계 목록 */
  setParticipantStats: SetParticipantStatDto[];
}
