/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export type SignInResponseDtoRole = typeof SignInResponseDtoRole[keyof typeof SignInResponseDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SignInResponseDtoRole = {
  PLAYER: 'PLAYER',
  PRO_PLAYER: 'PRO_PLAYER',
  REFEREE: 'REFEREE',
  HOPAE_ADMIN: 'HOPAE_ADMIN',
  HOST_ADMIN: 'HOST_ADMIN',
  HOST_CLERK_ORG_ADMIN: 'HOST_CLERK_ORG_ADMIN',
  HOST_CLERK_ORG_MEMBER: 'HOST_CLERK_ORG_MEMBER',
  REFEREE_V2: 'REFEREE_V2',
} as const;
