/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { SmsResponseDtoResult } from './smsResponseDtoResult';

export interface SmsResponseDto {
  /** Error message (returned only on failure) */
  error?: string;
  /** Response message */
  message: string;
  /** Aligo API response result (returned only on success) */
  result?: SmsResponseDtoResult;
  /** Success status */
  success: boolean;
}
