/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

/**
 * Aligo API response result (returned only on success)
 */
export type SmsResponseDtoResult = { [key: string]: unknown };
