/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { Bracket } from './bracket';
import type { Competition } from './competition';
import type { GameType } from './gameType';

export interface Stage {
  bracket: Bracket;
  competition: Competition;
  competitionId: number;
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
  gameType: GameType;
  gameTypeId: number;
  id: number;
  name: string;
  stageOrder: number;
  updatedAt: string;
}
