/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { MatchParticipantDto } from './matchParticipantDto';

export interface UpdateMatchParticipantsDto {
  /** Match ID */
  matchId: number;
  /** Array of roster IDs to add as participants */
  participants: MatchParticipantDto[];
}
