/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export type UpdateMatchDtoBestOf = typeof UpdateMatchDtoBestOf[keyof typeof UpdateMatchDtoBestOf];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateMatchDtoBestOf = {
  NUMBER_1: 1,
  NUMBER_3: 3,
  NUMBER_5: 5,
} as const;
