/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface UpdateParentAgreementDto {
  parentBirthday?: string;
  parentName?: string;
  parentParticipantConsent?: boolean;
  parentPhoneNumber?: string;
  parentSignature?: string;
  relationship?: string;
}
