/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { UpdateRoundDtoBestOf } from './updateRoundDtoBestOf';

export interface UpdateRoundDto {
  /** 1=단판, 3=3판2선승, 5=5판3선승 */
  bestOf?: UpdateRoundDtoBestOf;
  name?: string;
  refereeIds?: number[];
  scheduledDate?: string;
  scheduledTime?: string;
  venue?: string;
}
