/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

/**
 * 1=단판, 3=3판2선승, 5=5판3선승
 */
export type UpdateRoundDtoBestOf = typeof UpdateRoundDtoBestOf[keyof typeof UpdateRoundDtoBestOf];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateRoundDtoBestOf = {
  NUMBER_1: 1,
  NUMBER_3: 3,
  NUMBER_5: 5,
} as const;
