/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { UpdateMatchDtoBestOf } from './updateMatchDtoBestOf';

export interface UpdateMatchDto {
  bestOf?: UpdateMatchDtoBestOf;
  name?: string;
  refereeIds?: number[];
  scheduledDate?: string;
  scheduledTime?: string;
  venue?: string;
}
