/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface UploadScreenshotResponseDto {
  /** 스크린샷 URL */
  screenshotUrl: string;
}
