/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { Player } from './player';
import type { Referee } from './referee';

export interface User {
  /** Temporary */
  address?: string;
  createdAt: string;
  dateOfBirth: string;
  deletedAt?: string;
  email: string;
  gender: string;
  id: number;
  isForeigner: boolean;
  /** Temporary */
  lolMaxTier?: string;
  name: string;
  needCheck?: boolean;
  phoneNumber: string;
  /** Players */
  players: Player[];
  pushToken?: string;
  referee?: Referee;
  role: string;
  signature?: string;
  unique_key: string;
  /** Temporary */
  university?: string;
  updatedAt: string;
  userId: string;
}
