/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';

export interface VerifyCodeResponseDto {
  /** Error details (returned only on failure) */
  error?: string;
  /** Response message */
  message: string;
  /** Remaining verification attempts (returned only on failure) */
  remainingAttempts?: number;
  /** 성공 여부 */
  success: boolean;
  /** 사용자 정보 (성공 시에만 반환) */
  user?: User;
}
