/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */

export interface VerifyCodeDto {
  /** Verification code entered by the user */
  code: string;
  /** Verification request ID */
  requestId: string;
}
