/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { Host } from './host';
import type { Workspace } from './workspace';

export interface WorkspaceHost {
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
  host: Host;
  hostId: number;
  updatedAt: string;
  workspace: Workspace;
  workspaceId: string;
}
