/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Play.ID API
 * Esports API for Play.ID
 * OpenAPI spec version: 1.0
 */
import type { Organization } from './organization';

export interface Workspace {
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
  id: string;
  name: string;
  organization: Organization;
  organizationId: string;
  updatedAt: string;
}
